import { AllowedAttribute } from 'sanitize-html';

export const textTags = [
  'p',
  'h1',
  'h2',
  'strong',
  'span',
  'em',
  'u',
  's',
  'blockquote',
  'ol',
  'li',
  'ul',
  'a',
  'br',
];

export const allowedTagsSanitizer = [
  ...textTags,
  'address',
  'article',
  'aside',
  'footer',
  'header',
  'hgroup',
  'main',
  'nav',
  'section',
  'blockquote',
  'dd',
  'div',
  'dl',
  'dt',
  'figcaption',
  'figure',
  'hr',
  'main',
  'pre',
  'abbr',
  'b',
  'bdi',
  'bdo',
  'br',
  'cite',
  'code',
  'data',
  'dfn',
  'em',
  'i',
  'kbd',
  'mark',
  'q',
  'rb',
  'rp',
  'rt',
  'rtc',
  'ruby',
  's',
  'samp',
  'small',
  'sub',
  'sup',
  'time',
  'u',
  'caption',
  'col',
  'colgroup',
  'table',
  'tbody',
  'td',
  'tfoot',
  'th',
  'thead',
  'tr',
  'img',
  'iframe',
  'figure',
];

const defaultAttributes: Array<AllowedAttribute> = [
  'class',
  'width',
  'height',
  'alt',
  'target',
];

export const allowedAttributesSchema: Record<string, AllowedAttribute[]> = {
  figure: defaultAttributes,
  div: defaultAttributes,
  iframe: [...defaultAttributes, 'src', 'allowfullscreen', 'frameborder'],
  img: [...defaultAttributes, 'src'],
  address: defaultAttributes,
  article: defaultAttributes,
  aside: defaultAttributes,
  footer: defaultAttributes,
  header: defaultAttributes,
  h1: defaultAttributes,
  h2: defaultAttributes,
  h3: defaultAttributes,
  h4: defaultAttributes,
  h5: defaultAttributes,
  h6: defaultAttributes,
  hgroup: defaultAttributes,
  main: defaultAttributes,
  nav: defaultAttributes,
  section: defaultAttributes,
  blockquote: defaultAttributes,
  dd: defaultAttributes,
  dl: defaultAttributes,
  dt: defaultAttributes,
  figcaption: defaultAttributes,
  hr: defaultAttributes,
  li: defaultAttributes,
  ol: defaultAttributes,
  p: defaultAttributes,
  pre: defaultAttributes,
  ul: defaultAttributes,
  a: [...defaultAttributes, 'href', 'rel'],
  abbr: defaultAttributes,
  b: defaultAttributes,
  bdi: defaultAttributes,
  bdo: defaultAttributes,
  br: defaultAttributes,
  cite: defaultAttributes,
  code: defaultAttributes,
  data: defaultAttributes,
  dfn: defaultAttributes,
  em: defaultAttributes,
  i: defaultAttributes,
  kbd: defaultAttributes,
  mark: defaultAttributes,
  q: defaultAttributes,
  rb: defaultAttributes,
  rp: defaultAttributes,
  rt: defaultAttributes,
  rtc: defaultAttributes,
  ruby: defaultAttributes,
  s: defaultAttributes,
  samp: defaultAttributes,
  small: defaultAttributes,
  span: defaultAttributes,
  strong: defaultAttributes,
  sub: defaultAttributes,
  sup: defaultAttributes,
  time: defaultAttributes,
  u: defaultAttributes,
  var: defaultAttributes,
  wbr: defaultAttributes,
  caption: defaultAttributes,
  col: defaultAttributes,
  colgroup: defaultAttributes,
  table: defaultAttributes,
  tbody: defaultAttributes,
  td: defaultAttributes,
  tfoot: defaultAttributes,
  th: defaultAttributes,
  thead: defaultAttributes,
  tr: defaultAttributes,
};
export const allowedIframeHostnamesSchema = [
  'www.youtube.com',
  'player.vimeo.com',
  'www.google.com/maps',
  'www.facebook.com',
  'twitter.com',
  'www.tiktok.com',
];
